#!/bin/bash
m="\033[1;31m"
k="\033[1;33m"
h="\033[1;32m"
b="\033[1;34m"
n="\033[1;0m"

cekkoneksi(){
clear
echo -e $b"Checking internet Connection"$h" ."
sleep 1
clear
echo -e $b"Checking internet Connection"$h" .."
sleep 1
clear
echo -e $b"Checking internet Connection"$h" ..."
sleep 1
clear
echo -e $b"Checking internet Connection"$h" ...."
sleep 1 
clear
echo -e $b"Checking internet Connection"$h" ....."
sleep 1
clear
echo -e $b"Checking internet Connection"$h"[Harap tunggu]"
wget -q --tries=10 --timeout=20 --spider https://google.com
if [[ $? -eq 0 ]]; then
echo -e $h"[+] Dalam keadaan online !"$n
sleep 2
clear
echo -e $m"Sedang dalam proses upgrading"$k" ."
sleep 1
clear
echo -e $m"Sedang dalam proses upgrading"$k" .."
sleep 1
clear
echo -e $m"Sedang dalam proses upgrading"$k" ..."
sleep 1
clear
echo -e $m"Sedang dalam proses upgrading"$k" ...."
sleep 1
clear
echo -e $m"Sedang dalam proses upgrading"$k" ....."
sleep 1
apt upgrade -y > /dev/null 2>&1
apt autoremove -y > /dev/null 2>&1
if [[ $? -eq 0 ]]; then
echo "Selesai Upgrade"
clear
else
echo "Gagal Upgrade"
clear
fi
clear
else 
clear
echo -e $m "[+]Maaf anda sedang dalam keadaan offline"
sleep 2
clear
exit
fi
}

if [[ $? -eq 0 ]]; then
clear
 if [[ `whoami` == 'root' ]]; then
 clear
echo -e $b"You are root"
	cekkoneksi
else
	clear
echo -e $h"[+] Harus sebagai root."
   sudo su
fi
exit
fi


