#!/bin/bash
m="\033[1;31m"
k="\033[1;33m"
h="\033[1;32m"
b="\033[1;34m"
n="\033[1;0m"
clear
echo -e "========  ==     ==  ====   "$m"GNU/Linux Sragen Versi 1"
echo -e "==        ==     ==  =      "$k"Website : glis-linux.com"
echo -e "==  ====  ==     ==  ====   "$h"Repo : github.com/operatingsystemSRAGEN/glis"
echo -e "==   ===  ==     ==     =   "$b"Harus di Update sebelum :"$n"1 Desember 2017"
echo -e "========  =====  ==  ====   "$n"Author : Developer Team GNU/Linux Sragen"
